name: NDST
channels:
  - conda-forge
dependencies:
  - python=3.7.6
  - ipython
  - jupyter
  - notebook
  - ipykernel
  - matplotlib
  - pyyaml
  - numpy
  - scipy
  - xarray
  - netcdf4
  - pandas
  - geopandas
  - gdal
  - fiona
  - rasterio
  - r-base
  - r-gbm
  - shapely
  - rtree
  - pyproj=2.6.1.post1
  - pyshp
  - rpy2=2.9.4
  - openpyxl
  - xlrd
  - pytest
  - pytest-cov
