name: NDST
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24.3
  - gdal
  - scikit-learn=1.2.1  
  - scipy=1.10  
  - matplotlib
  - netcdf4
  - notebook
  - jupyter 
  - jupyterlab
  - joblib  
  - pytest
  - flopy    
  - pandas= 2.0.1
  - pip
  - proj
  - xarray
  - fiona
  - geopandas 
  - rtree
  - pyproj>=3.4
  - pyshp  
  - rasterio>=1.3 
  - descartes  
  - hydrofunctions  
  - openpyxl  
  - pytest
  - pytest-cov
